* Working through OvermindDL1's Bucklescript-tea tutorial
- 1st part: http://blog.overminddl1.com/posts/bucklescript-tea-game-overbots-pt1-setup/
- setup on Debian/Ubuntu: sudo apt-get install nodejs npm
- git clone this repo
- npm install
- npm run build
- open release/dev.html in your browser: 42!

** DONE gotchas in 1st part / missing in tut
http://blog.overminddl1.com/posts/bucklescript-tea-game-overbots-pt1-setup/

- npm install npm-run-all: for run-s, run-p used in package.json script section
- 1st part: npm run build does not work with empty scss file (filled in 2nd part)
- rollup.config.js needs:
  - import node_resolve from 'rollup-plugin-node-resolve';
    - see: https://github.com/tcoopman/bucklescript-tea-starter-kit/blob/master/configs/rollup.development.js
      - livereload possible, too
  - plugins: [
      node_resolve({ module: true, browser: true })
    ]
  - rollup config format change: see rollup.config.js
- some warnings regarding npm and node v10.24.0 (current standard in Debian Buster), but so far alright! (maybe use yarn as npm replacement?)

** gotchas in 2nd part
*** short hand record syntax vs. explicit module function
#+BEGIN_SRC diff
 let main =
   App.standardProgram {
-    init;
-    update;
-    view;
-    subscriptions;
+    init = init;
+    update = update;
+    view = Overbots_view.view;
+    subscriptions = subscriptions;
 }
#+END_SRC
changing above or:

"Error: Unbound record field Overbots_view.init"

* Reading
**  types as sets
*** product types ("records") vs. sum types ("enums")
- https://guide.elm-lang.org/appendix/types_as_sets.html
  - Bool/bool is a sum type: two values, either true or false (cardinality of two)
  - product types have standard OCaml syntax of asterisk (*) as infix tuple constructor
    - OCaml: value of (True, False) has type (bool * bool), forming the product of two sum types by multiplication (*)
    - Elm: value of (True, False) has type (Bool, Bool)
*** TODO Haskell/Elm types vs. Ocaml types
**** OCaml
#+BEGIN_SRC ocaml
type state =
  | Running
  | Paused of int

type 'model debug_model = {
  history : (string * 'model) list;
  state : state;
  show_details : bool;
}
#+END_SRC
[[https://github.com/OvermindDL1/bucklescript-tea/blob/master/src-ocaml/tea_debug.ml][source]]
